"""init

Revision ID: 61970540eed7
Revises: 
Create Date: 2022-01-29 22:59:32.550926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61970540eed7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Уникальный номер', sa.String(length=36), nullable=True),
    sa.Column('Дата и время создания', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Дата и время обновления', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Наименование поставщика', sa.String(length=255), nullable=True),
    sa.Column('Адрес поставщика', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Адрес поставщика'),
    sa.UniqueConstraint('Наименование поставщика')
    )
    op.create_index(op.f('ix_flights_providers_Уникальный номер'), 'flights_providers', ['Уникальный номер'], unique=False)
    op.create_table('flights_requests',
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Уникальный номер', sa.String(length=36), nullable=True),
    sa.Column('Дата и время создания', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('Дата и время обновления', sa.DateTime(timezone=True), nullable=True),
    sa.Column('Дата отправки', sa.Date(), nullable=True),
    sa.Column('Город отправления', sa.String(length=255), nullable=True),
    sa.Column('Код валюты клиента', sa.String(length=5), nullable=True),
    sa.Column('Дата отправки обратно', sa.Date(), nullable=True),
    sa.Column('Город отправления обратно', sa.String(length=255), nullable=True),
    sa.Column('Обратный билет', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_requests_Уникальный номер'), 'flights_requests', ['Уникальный номер'], unique=False)
    op.create_table('flights_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Уникальный номер', sa.String(length=36), nullable=True),
    sa.Column('Дата и время отправки', sa.DateTime(), nullable=True),
    sa.Column('Дата и время прибытия', sa.DateTime(), nullable=True),
    sa.Column('Код города отправки', sa.String(length=5), nullable=True),
    sa.Column('Код города прибытия', sa.String(length=5), nullable=True),
    sa.Column('Цена билета', sa.Float(precision=2), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('Уникальный номер результата запроса', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Уникальный номер результата запроса'], ['flights_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_info_Код города отправки'), 'flights_info', ['Код города отправки'], unique=False)
    op.create_index(op.f('ix_flights_info_Уникальный номер'), 'flights_info', ['Уникальный номер'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_info_Уникальный номер'), table_name='flights_info')
    op.drop_index(op.f('ix_flights_info_Код города отправки'), table_name='flights_info')
    op.drop_table('flights_info')
    op.drop_index(op.f('ix_flights_requests_Уникальный номер'), table_name='flights_requests')
    op.drop_table('flights_requests')
    op.drop_index(op.f('ix_flights_providers_Уникальный номер'), table_name='flights_providers')
    op.drop_table('flights_providers')
    # ### end Alembic commands ###
